[package]
name = "maarco"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
clap = { version = "4.5.48", features = ["derive"] }
clap_derive = "4.5.47"
cross = "0.2.5"
crossterm = "0.29.0"

eyre = "0.6.12"
nmea = { version = "0.7.0", features = ["default"]}
serialport = "4.7.3"
