[project]
name = "maarco"
version = "0.1.0"
description = "Code for MAARCO"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygpsclient>=1.5.14",
    "pynmeagps>=1.0.53",
    "pyrtcm>=1.1.9",
]
